### ISSUE TITLE
Noticing deprecation warnings?

### ISSUE THREAD

**Issue by jeanconn** [sot/testr#9]
@taldcroft Do you have any thoughts about how we could hightlight/become more aware of warnings (especially package deprecation warnings) when using this suite?  We probably would like to know if our code is going to trigger those when testing out a new runtime environment with a shiny new numpy/scipy/matplotlib.

Should we have a convention to set test code to use a warnings filter so all warnings are handled as errors or some such?

**Comment by taldcroft** [comment]
I had the same thoughts. Not immediately clear how to make this happen but agreed that it is important.

**Comment by taldcroft** [comment]
I think this can be done by means of a `post_process` script that essentially greps for `warning` or `error` in the log file(s).  The other element of this is running pytest with `-s` always so that warnings show up.  In other testing that is done without pytest then those warnings should just show up.

**Comment by jeanconn** [comment]
On Mon, Oct 10, 2016 at 9:57 AM, Tom Aldcroft <notifications@github.com>
wrote:

> I think this can be done by means of a post_process script
>
I like that.​

**Comment by taldcroft** [comment]
Closed by 13883982.
